<?php
$data = array (
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '中国购',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '122',
    'name' => '中国购',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '特产干货',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '124',
    'name' => '特产干货',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '90',
    'level' => 1,
    'id' => '123',
    'name' => '休闲零食',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '立即购',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '77',
    'name' => '立即购',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '酒水类',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '酒水类',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '葡萄酒',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 3,
    'id' => '88',
    'name' => '红葡萄酒',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '89',
    'name' => '白葡萄酒',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '冰酒',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 3,
    'id' => '87',
    'name' => '冰酒',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 2,
    'id' => '93',
    'name' => '果汁',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '水',
    'measure_unit' => '',
    'parent_id' => '83',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '水',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '矿泉水',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 3,
    'id' => '91',
    'name' => '矿泉水',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '气泡水',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 3,
    'id' => '92',
    'name' => '气泡水',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '日用品类',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '日用品类',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '清洁洗涤',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 2,
    'id' => '99',
    'name' => '清洁洗涤',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '纸类',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '纸类',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '厨房用纸',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 3,
    'id' => '97',
    'name' => '厨房用纸',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '生活用纸',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 3,
    'id' => '98',
    'name' => '生活用纸',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '空气清新剂',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '132',
    'name' => '空气清新剂',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '粮油类',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '134',
    'name' => '粮油类',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '135',
    'name' => '食用油',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '食品类',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '125',
    'name' => '食品类',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '薯片爆米花',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '136',
    'name' => '薯片爆米花',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '38',
    'level' => 2,
    'id' => '133',
    'name' => '糖果',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '42',
    'level' => 2,
    'id' => '127',
    'name' => '坚果',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '果干',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 2,
    'id' => '128',
    'name' => '果干',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 2,
    'id' => '138',
    'name' => '饼干糕点',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '枫糖蜂蜜',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 2,
    'id' => '126',
    'name' => '枫糖蜂蜜',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '母婴类',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '129',
    'name' => '母婴类',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '尿片尿裤',
    'measure_unit' => '',
    'parent_id' => '129',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '130',
    'name' => '尿片尿裤',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '湿巾',
    'measure_unit' => '',
    'parent_id' => '129',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '131',
    'name' => '湿巾',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '跨境购',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '78',
    'name' => '跨境购',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '轻奢',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '105',
    'name' => '轻奢',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '精品包包',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '137',
    'name' => '精品包包',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '保健品',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '106',
    'name' => '保健品',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '日用品',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '107',
    'name' => '日用品',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '清洁洗涤',
    'measure_unit' => '',
    'parent_id' => '107',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '30',
    'level' => 2,
    'id' => '119',
    'name' => '清洁洗涤',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '107',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '54',
    'level' => 2,
    'id' => '116',
    'name' => '个人护理',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '尿片尿裤',
    'measure_unit' => '',
    'parent_id' => '107',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 2,
    'id' => '120',
    'name' => '尿片尿裤',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '纸品湿巾',
    'measure_unit' => '',
    'parent_id' => '107',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '121',
    'name' => '纸品湿巾',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '厨房用品',
    'measure_unit' => '',
    'parent_id' => '107',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 2,
    'id' => '118',
    'name' => '厨房用品',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '食品',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 1,
    'id' => '102',
    'name' => '食品',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '糖果口香糖',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 2,
    'id' => '109',
    'name' => '糖果口香糖',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '饼干薯片',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 2,
    'id' => '112',
    'name' => '饼干薯片',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '果干果泥',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 2,
    'id' => '104',
    'name' => '果干果泥',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '麦片',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 2,
    'id' => '110',
    'name' => '麦片',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '果汁饮料茶',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '113',
    'name' => '果汁饮料茶',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '意粉',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '117',
    'name' => '意粉',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 2,
    'id' => '114',
    'name' => '咖啡',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '31',
    'level' => 2,
    'id' => '108',
    'name' => '巧克力',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '103',
    'name' => '坚果',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '枫糖蜂蜜',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '111',
    'name' => '枫糖蜂蜜',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '102',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 2,
    'id' => '115',
    'name' => '调味品',
  ),
);
?>